# Generated by Django 6.0 on 2025-12-06 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('cover_image', models.ImageField(upload_to='audiobook_covers/', verbose_name='Обложка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Аудиокнига',
                'verbose_name_plural': 'Аудиокниги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('fantasy', 'Фантастика'), ('detective', 'Детектив'), ('scifi', 'Научная фантастика'), ('classic', 'Классика'), ('nonfiction', 'Нехудожественная литература')], max_length=50, verbose_name='Жанр')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Обложка')),
                ('match_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент совпадения')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новая')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
                ('icon_class', models.CharField(help_text='Например: fa-solid fa-users', max_length=50, verbose_name='Класс иконки')),
                ('color_class', models.CharField(default='bg-white', max_length=50, verbose_name='Класс цвета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа форума',
                'verbose_name_plural': 'Группы форума',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarqueeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение бегущей строки',
                'verbose_name_plural': 'Сообщения бегущей строки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('goal', models.PositiveIntegerField(verbose_name='Цель (количество книг)')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='Текущий прогресс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Книжный марафон',
                'verbose_name_plural': 'Книжные марафоны',
            },
        ),
        migrations.CreateModel(
            name='RecommendationQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('category', models.CharField(choices=[('review', 'Рецензия'), ('discussion', 'Обсуждение'), ('question', 'Вопрос'), ('news', 'Новость')], max_length=20, verbose_name='Категория')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('forum_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exlib_app.forumgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пост форума',
                'verbose_name_plural': 'Посты форума',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('genre_weights', models.JSONField(help_text='JSON с весами для жанров', verbose_name='Веса жанров')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Exlib_app.recommendationquiz')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('karma', models.IntegerField(default=0, verbose_name='Карма')),
                ('reading_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exlib_app.readingchallenge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Читаю'), ('planned', 'В планах'), ('read', 'Прочитано'), ('abandoned', 'Брошено')], default='planned', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exlib_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус книги пользователя',
                'verbose_name_plural': 'Статусы книг пользователей',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
